### ISSUE TITLE
Prod version is missing the responsive styles

### ISSUE THREAD

**Issue by chrisvidal** [cjkpl/oc-tabularasa-theme#5]
when I run `npm run prod` the app.css result is missing some styles.
I noticed easily that all the Tailwind responsive class are missing (the `md:`, `lg:`, ...).

would you have any idea why?

thanks

**Comment by cjkpl** [comment]
Hi Chris,

It should maintain all responsive variants that are in use at the moment it was called.

npm prod prunes all unused styles - so you will not have in your site any styles that were not present in the templates at the point of compilation of the css files (i.e. executing npm prod). With Tailwindcss, there is no other choice, as the "full" file would be > 1Mb. 

As a result, if you e.g. try to edit your cms pages using the backend / web interface, on the server, you will quickly bump into styles that are not in the css file.

Does it help in your case?

**Comment by chrisvidal** [comment]
thanks for taking the time to answer

To clarify:

do you mean to say that if I use tailwind classes directly in `.htm` file like this for instance `<div class="md:max-w-5xl">View<div>` that the prod CSS build process will ignore the class `md:max-w-5xl`? Attending that this class is not used in any of the rest of .scss existing code.

I believe that would be going against the philosophy of Tailwind itself as a utility framework?

**Comment by cjkpl** [comment]
Hi Chris,

> if I use tailwind classes directly in .htm file like this for instance <div class="md:max-w-5xl">View<div>

If you use on your localhost, inside your theme folder, before running ```npm run prod``` then no, purge will include it properly. If you use it after ```npm run prod``` (or on production server, where you may not have ```npm``` available) to modify template, then clearly that class will not be available.

There is one more use case which may cause problems - if you create your own plugins, and add components with twig templates inside the plugins folder - this folder is not included in purge scan by default, so it will not keep classes used in the template. For your plugin component templates to be styled properly, you should add your own plugins folder to tailwind config - for example my own looks like this:
```js
...
    "purge": [
        "./assets/src/**/*.vue",
        "./layouts/**/*.htm",
        "./pages/**/*.htm",
        "./partials/**/*.htm",
        './../../plugins/cjkpl/**/*.htm',
    ],
...
```

**Comment by chrisvidal** [comment]
you are so good! that's it indeed, I totally missed the fact that this particular .htm was in the plugin components.
thanks a bunch!
